src/main/kotlin/com/yourssu/scouter/hrms/application/domain/member/MemberController.kt
src/main/kotlin/com/yourssu/scouter/hrms/business/domain/member/MemberService.kt

- 멤버 역할 목록 조회 api 추가
- 멤버 상태 목록 조회 api 추가
- closed #11

feat: #11 멤버 역할/상태 목록 조회 기능 추가

---

src/main/kotlin/com/yourssu/scouter/common/application/domain/department/DepartmentController.kt
src/main/kotlin/com/yourssu/scouter/common/business/domain/department/DepartmentService.kt
src/main/kotlin/com/yourssu/scouter/common/implement/domain/department/DepartmentReader.kt
src/main/kotlin/com/yourssu/scouter/common/implement/domain/department/DepartmentRepository.kt
src/main/kotlin/com/yourssu/scouter/common/storage/domain/department/DepartmentRepositoryImpl.kt
src/main/kotlin/com/yourssu/scouter/common/storage/domain/department/JpaDepartmentRepository.kt

- 단과대로 필터링하지 않은 전체 학과 목록 조회 api 추가
- 가나다 순으로 정렬되어서 반환
- closed #21

feat: #21 학과 전체 목록 조회 기능 추가

---

src/main/kotlin/com/yourssu/scouter/hrms/application/domain/member/MemberController.kt
src/main/kotlin/com/yourssu/scouter/hrms/business/domain/member/MemberService.kt
src/main/kotlin/com/yourssu/scouter/hrms/implement/domain/member/MemberReader.kt
src/main/kotlin/com/yourssu/scouter/hrms/implement/domain/member/MemberRepository.kt
src/main/kotlin/com/yourssu/scouter/hrms/storage/domain/member/JpaMemberRepository.kt
src/main/kotlin/com/yourssu/scouter/hrms/storage/domain/member/MemberRepositoryImpl.kt

- 멤버 검색 api 추가
- 멤버 상태 기준 필터링 api 추가
- closed #12

feat: #12 멤버 검색 및 상태 필터링 기능 추가

---

src/main/kotlin/com/yourssu/scouter/ats/application/domain/applicant/ApplicantController.kt
src/main/kotlin/com/yourssu/scouter/ats/business/domain/applicant/ApplicantService.kt
src/main/kotlin/com/yourssu/scouter/ats/implement/domain/applicant/ApplicantReader.kt
src/main/kotlin/com/yourssu/scouter/ats/implement/domain/applicant/ApplicantRepository.kt
src/main/kotlin/com/yourssu/scouter/ats/storage/domain/applicant/ApplicantRepositoryImpl.kt
src/main/kotlin/com/yourssu/scouter/ats/storage/domain/applicant/JpaApplicantRepository.kt

- 지원자 검색 기능 추가
- 지원자 상태를 기준으로 필터링해서 조회하는 기능 추가
- 학기별 지원자 목록 필터링 기능 추가
- closed #19

feat: #19 지원자 검색 및 상태 필터링 기능 추가

---

src/main/kotlin/com/yourssu/scouter/common/application/domain/semester/ReadSemesterResponse.kt
src/main/kotlin/com/yourssu/scouter/common/application/domain/semester/SemesterController.kt
src/main/kotlin/com/yourssu/scouter/common/business/domain/semester/SemesterService.kt
src/main/kotlin/com/yourssu/scouter/common/implement/domain/semester/SemesterReader.kt
src/main/kotlin/com/yourssu/scouter/common/implement/domain/semester/SemesterRepository.kt
src/main/kotlin/com/yourssu/scouter/common/storage/domain/semester/SemesterRepositoryImpl.kt

feat: #27 학기 목록 조회 기능 추가

---

src/main/kotlin/com/yourssu/scouter/ats/application/domain/applicant/CreateApplicantRequest.kt
src/main/kotlin/com/yourssu/scouter/ats/application/domain/applicant/UpdateApplicantRequest.kt
src/main/kotlin/com/yourssu/scouter/ats/implement/domain/applicant/ApplicantReader.kt
src/main/kotlin/com/yourssu/scouter/ats/implement/support/exception/ApplicantNotFoundException.kt
src/main/kotlin/com/yourssu/scouter/common/application/support/exception/CommonExceptionHandler.kt
src/main/kotlin/com/yourssu/scouter/common/application/support/exception/ExceptionResponse.kt
src/main/kotlin/com/yourssu/scouter/common/implement/domain/department/DepartmentReader.kt
src/main/kotlin/com/yourssu/scouter/common/implement/domain/part/PartReader.kt
src/main/kotlin/com/yourssu/scouter/common/implement/domain/semester/SemesterReader.kt
src/main/kotlin/com/yourssu/scouter/common/implement/support/exception/CustomException.kt
src/main/kotlin/com/yourssu/scouter/common/implement/support/exception/DepartmentNotFoundException.kt
src/main/kotlin/com/yourssu/scouter/common/implement/support/exception/PartNotFoundException.kt
src/main/kotlin/com/yourssu/scouter/common/implement/support/exception/SemesterNotFoundException.kt
src/main/kotlin/com/yourssu/scouter/hrms/application/domain/member/CreateMemberRequest.kt
src/main/kotlin/com/yourssu/scouter/hrms/implement/domain/member/MemberReader.kt
src/main/kotlin/com/yourssu/scouter/hrms/implement/support/exception/MemberNotFoundException.kt

- 커스텀 예외를 `implement.support.exception`패키지로 이동
- ExceptionHandler 추가 및 커스텀 예외 처리
- closed #30

feat: #30 ExceptionHandler 추가

---

.gitignore
build.gradle.kts
src/main/kotlin/com/yourssu/scouter/common/implement/support/configuration/PropertiesConfiguration.kt
src/main/kotlin/com/yourssu/scouter/common/implement/support/exception/InvalidTokenException.kt
src/main/kotlin/com/yourssu/scouter/common/implement/support/security/token/JwtProperties.kt
src/main/kotlin/com/yourssu/scouter/common/implement/support/security/token/JwtTokenProcessor.kt
src/main/kotlin/com/yourssu/scouter/common/implement/support/security/token/TokenProcessor.kt
src/main/kotlin/com/yourssu/scouter/common/implement/support/security/token/TokenType.kt
src/main/resources/application-local.yml
src/test/kotlin/com/yourssu/scouter/common/implement/support/security/token/JwtTokenProcessorTest.kt

- Jwt 인코딩 기능 추가
- Jwt 디코딩 기능 추가
- closed #32

feat: #32 Jwt 인코딩/디코딩 기능 추가

---

src/main/kotlin/com/yourssu/scouter/hrms/business/domain/member/CreateMemberCommand.kt
src/main/kotlin/com/yourssu/scouter/hrms/business/domain/member/MemberService.kt
src/main/kotlin/com/yourssu/scouter/hrms/implement/domain/member/ActiveMember.kt
src/main/kotlin/com/yourssu/scouter/hrms/implement/domain/member/ActiveMemberRepository.kt
src/main/kotlin/com/yourssu/scouter/hrms/implement/domain/member/MemberRepository.kt
src/main/kotlin/com/yourssu/scouter/hrms/implement/domain/member/MemberWriter.kt
src/main/kotlin/com/yourssu/scouter/hrms/storage/domain/member/ActiveMemberEntity.kt
src/main/kotlin/com/yourssu/scouter/hrms/storage/domain/member/ActiveMemberRepositoryImpl.kt
src/main/kotlin/com/yourssu/scouter/hrms/storage/domain/member/GraduatedMemberEntity.kt
src/main/kotlin/com/yourssu/scouter/hrms/storage/domain/member/GraduatedMemberRepositoryImpl.kt
src/main/kotlin/com/yourssu/scouter/hrms/storage/domain/member/InactiveMemberEntity.kt
src/main/kotlin/com/yourssu/scouter/hrms/storage/domain/member/InactiveMemberRepositoryImpl.kt
src/main/kotlin/com/yourssu/scouter/hrms/storage/domain/member/JpaMemberRepository.kt
src/main/kotlin/com/yourssu/scouter/hrms/storage/domain/member/MemberEntity.kt
src/main/kotlin/com/yourssu/scouter/hrms/storage/domain/member/MemberRepositoryImpl.kt
src/main/kotlin/com/yourssu/scouter/hrms/storage/domain/member/WithdrawnMemberEntity.kt
src/main/kotlin/com/yourssu/scouter/hrms/storage/domain/member/WithdrawnMemberRepositoryImpl.kt

- 액티브 멤버 저장 service 추가
- 액티브 멤버 회비 납부 여부 기본값은 false로 설정
- closed #45

feat: #45 액티브 멤버 저장 기능 추가

---

src/main/kotlin/com/yourssu/scouter/ats/application/domain/applicant/ApplicantController.kt
src/main/kotlin/com/yourssu/scouter/ats/business/domain/applicant/ApplicantService.kt

- 지원자 상태 목록 조회 api 추가
- closed #57

feat: #57 지원자 상태 목록 조회 api 추가

---

src/main/kotlin/com/yourssu/scouter/common/application/domain/authentication/AuthenticationController.kt
src/main/kotlin/com/yourssu/scouter/common/application/domain/authentication/WithdrawalRequest.kt
src/main/kotlin/com/yourssu/scouter/common/business/domain/authentication/AuthenticationService.kt
src/main/kotlin/com/yourssu/scouter/common/implement/domain/user/UserRepository.kt
src/main/kotlin/com/yourssu/scouter/common/implement/domain/user/UserWriter.kt
src/main/kotlin/com/yourssu/scouter/common/storage/domain/user/UserRepositoryImpl.kt

feat: #61 회원 탈퇴 기능 추가

---

src/main/kotlin/com/yourssu/scouter/common/application/support/exception/CommonExceptionHandler.kt
src/main/kotlin/com/yourssu/scouter/common/business/domain/authentication/OAuth2Service.kt
src/main/kotlin/com/yourssu/scouter/common/implement/support/security/oauth2/GoogleOAuth2Handler.kt
src/main/kotlin/com/yourssu/scouter/common/implement/support/security/oauth2/GoogleUserApiClient.kt

- 구글 사용자 정보 가져올 때 null 값 허용
- 로그아웃 후 재로그인 시 예외가 발생하는 문제 해결
- 전역 예외처리 핸들러 추가
- 예외처리 핸들러에 로깅 추가
- closed #68

fix: #68 회원가입, 재로그인 시 발생하는 오류 해결

---

src/main/kotlin/com/yourssu/scouter/common/application/support/exception/CommonExceptionHandler.kt
src/main/kotlin/com/yourssu/scouter/common/business/domain/authentication/OAuth2Service.kt
src/main/kotlin/com/yourssu/scouter/common/implement/support/security/oauth2/GoogleOAuth2Handler.kt
src/main/kotlin/com/yourssu/scouter/common/implement/support/security/oauth2/GoogleUserApiClient.kt

Reverts yourssu/Yourssu-Scouter-Backend#69

Revert "fix: #68 회원가입, 재로그인 시 발생하는 오류 해결"

---

src/main/kotlin/com/yourssu/scouter/common/application/support/configuration/CorsProperties.kt
src/main/kotlin/com/yourssu/scouter/common/application/support/configuration/WebConfiguration.kt
src/main/resources/application-local.yml

- application.yml에서 cors 설정에 추가할 origins 가져오도록 구현
- cors 값 바뀔 때마다 코드를 수정하지 않아도 됨 (yml 파일만 수정하고 재배포하면 됨)
- closed #66

feat: #66 cors 설정 추가

---

src/main/kotlin/com/yourssu/scouter/common/application/support/authentication/LoginInterceptor.kt
src/main/kotlin/com/yourssu/scouter/common/application/support/configuration/WebConfiguration.kt

- Preflight 요청(OPTIONS 요청)일 경우 인터셉터를 바로 통과할 수 있도록 함
- closed #79

fix: #79  Preflight 요청에 대한 cors 에러 해결

---

src/main/kotlin/com/yourssu/scouter/ats/application/domain/applicant/ApplicantSyncController.kt
src/main/kotlin/com/yourssu/scouter/ats/application/domain/applicant/LastSyncTimeResponse.kt
src/main/kotlin/com/yourssu/scouter/ats/business/domain/applicant/ApplicantSyncService.kt
src/main/kotlin/com/yourssu/scouter/ats/implement/domain/applicant/ApplicantSyncLogReader.kt
src/main/kotlin/com/yourssu/scouter/ats/implement/domain/applicant/ApplicantSyncLogRepository.kt
src/main/kotlin/com/yourssu/scouter/ats/storage/domain/applicant/ApplicantSyncLogRepositoryImpl.kt
src/main/kotlin/com/yourssu/scouter/ats/storage/domain/applicant/JpaApplicantSyncLogRepository.kt

마지막으로 지원자 정보를 불러온 시간을 조회하는 기능 추가
- closed #83

feat: #83 마지막으로 지원자 정보를 불러온 시간을 조회하는 기능 추가

---

src/main/kotlin/com/yourssu/scouter/ats/application/domain/applicant/ApplicantSyncController.kt
src/main/kotlin/com/yourssu/scouter/ats/application/domain/applicant/LastApplicantSyncTimeResponse.kt
src/main/kotlin/com/yourssu/scouter/hrms/application/domain/member/LastMemberSyncTimeResponse.kt
src/main/kotlin/com/yourssu/scouter/hrms/application/domain/member/MemberController.kt
src/main/kotlin/com/yourssu/scouter/hrms/application/domain/member/MemberSyncController.kt
src/main/kotlin/com/yourssu/scouter/hrms/application/domain/member/MemberSyncResponse.kt
src/main/kotlin/com/yourssu/scouter/hrms/business/domain/member/MemberSyncService.kt
src/main/kotlin/com/yourssu/scouter/hrms/implement/domain/member/MemberSyncLog.kt
src/main/kotlin/com/yourssu/scouter/hrms/implement/domain/member/MemberSyncLogReader.kt
src/main/kotlin/com/yourssu/scouter/hrms/implement/domain/member/MemberSyncLogRepository.kt
src/main/kotlin/com/yourssu/scouter/hrms/implement/domain/member/MemberSyncLogWriter.kt
src/main/kotlin/com/yourssu/scouter/hrms/storage/domain/member/JpaMemberSyncLogRepository.kt
src/main/kotlin/com/yourssu/scouter/hrms/storage/domain/member/MemberSyncLogEntity.kt
src/main/kotlin/com/yourssu/scouter/hrms/storage/domain/member/MemberSyncLogRepositoryImpl.kt

마지막으로 합격자 정보를 멤버로 동기화한 시간을 조회 api 추가
- closed #87

feat: #87 마지막으로 합격자 정보를 멤버로 동기화한 시간을 조회하는 기능 추가

---

src/main/kotlin/com/yourssu/scouter/hrms/business/domain/member/MemberService.kt
src/main/kotlin/com/yourssu/scouter/hrms/implement/domain/member/Member.kt
src/main/kotlin/com/yourssu/scouter/hrms/implement/support/exception/IllegalMemberException.kt

- 멤버 비고란 길이 검증 추가
- 멤버 정보 변경 로직 리팩토링
- closed #89

feat: #89 멤버 비고란 길이 검증 추가 및 멤버 정보 변경 로직 리팩토링

---

src/main/kotlin/com/yourssu/scouter/ats/application/domain/applicant/ApplicantController.kt
src/main/kotlin/com/yourssu/scouter/ats/business/domain/applicant/ApplicantService.kt
src/main/kotlin/com/yourssu/scouter/hrms/application/domain/member/MemberController.kt
src/main/kotlin/com/yourssu/scouter/hrms/business/domain/member/MemberService.kt

- 멤버 목록 조회 시 파트 필터링 추가
- 지원자 목록 조회 시 파트 필터링 추가
- closed #94

feat: #94 멤버 목록 조회, 지원자 목록 조회 시 파트 필터링 추가

---

src/main/kotlin/com/yourssu/scouter/common/application/domain/semester/ReadSemesterResponse.kt
src/main/kotlin/com/yourssu/scouter/common/application/domain/semester/SemesterController.kt
src/main/kotlin/com/yourssu/scouter/common/business/domain/semester/SemesterService.kt
src/main/kotlin/com/yourssu/scouter/common/business/support/utils/SemesterConverter.kt
src/main/kotlin/com/yourssu/scouter/common/implement/domain/semester/Semester.kt
src/main/kotlin/com/yourssu/scouter/common/implement/domain/semester/SemesterReader.kt

- 현재 날짜에 해당하는 학기 정보 조회 api 추가
- 학기 변환 관련 로직 리팩토링
- closed #96

feat: #96 현재 날짜에 해당하는 학기 정보 조회 기능 추가

---

src/main/kotlin/com/yourssu/scouter/common/application/domain/semester/SemesterController.kt
src/main/kotlin/com/yourssu/scouter/common/business/domain/semester/SemesterService.kt

- 학기 목록 조회 시 내림차순 정렬 상태로 응답하도록 변경
- closed #99

refactor: #99 학기 목록 조회 시 내림차순 정렬 상태로 응답하도록 변경

---

.github/workflows/claude-issue-comment.yml
.github/workflows/claude-issue.yml
.github/workflows/claude-pr.yml

클로드 코드 액션을 위한 워크플로우 추가
closed #116

[#116]; chore: Claude code action 추가

---

src/main/kotlin/com/yourssu/scouter/common/application/support/configuration/SwaggerConfiguration.kt
src/main/resources/application-dev.yml
src/main/resources/application-local.yml

refreshURL과 tokenURL이 environment 에 따라 변경되도록 했습니다.
closed #120

fix: tokenURL과 refreshURL이 환경 종속적이지 않게 변경

---

src/main/kotlin/com/yourssu/scouter/ats/implement/domain/recruiter/InterviewSchedule.kt
src/main/kotlin/com/yourssu/scouter/ats/implement/domain/recruiter/ScheduleReader.kt
src/main/kotlin/com/yourssu/scouter/ats/implement/domain/recruiter/ScheduleRepository.kt
src/main/kotlin/com/yourssu/scouter/ats/implement/domain/recruiter/ScheduleWriter.kt
src/main/kotlin/com/yourssu/scouter/ats/storage/domain/recruiter/JpaScheduleRepository.kt
src/main/kotlin/com/yourssu/scouter/ats/storage/domain/recruiter/ScheduleEntity.kt
src/main/kotlin/com/yourssu/scouter/ats/storage/domain/recruiter/ScheduleRepositoryImpl.kt
src/main/kotlin/com/yourssu/scouter/ats/storage/domain/support/exception/DuplicateScheduleException.kt

면접 계획 생성을 위한 레포지토리 레이어를 구현합니다.
- Reader / Writer
- Repository
- RepositoryImpl
- Entity
closed #139

[#139]; feat: 면접 계획 생성을 위한 레포지토리 레이어 구현
