yourssu/Yourssu-Scouter-Backend

- src/main/kotlin/com/yourssu/scouter/common/application/domain/college/CollegeController.kt
- src/main/kotlin/com/yourssu/scouter/common/application/domain/college/ReadCollegeResponse.kt
- src/main/kotlin/com/yourssu/scouter/common/business/domain/college/CollegeDto.kt
- src/main/kotlin/com/yourssu/scouter/common/business/domain/college/CollegeService.kt
- src/main/kotlin/com/yourssu/scouter/common/business/domain/college/ReadCollegesResult.kt
- src/main/kotlin/com/yourssu/scouter/common/implement/domain/college/College.kt
- src/main/kotlin/com/yourssu/scouter/common/implement/domain/college/CollegeReader.kt
- src/main/kotlin/com/yourssu/scouter/common/implement/domain/college/CollegeRepository.kt
- src/main/kotlin/com/yourssu/scouter/common/implement/support/initialization/DataInitializer.kt
- src/main/kotlin/com/yourssu/scouter/common/implement/support/initialization/InitialColleges.kt
- src/main/kotlin/com/yourssu/scouter/common/storage/domain/college/CollegeEntity.kt
- src/main/kotlin/com/yourssu/scouter/common/storage/domain/college/CollegeRepositoryImpl.kt
- src/main/kotlin/com/yourssu/scouter/common/storage/domain/college/JpaCollegeRepository.kt
- 단과대 도메인 엔티티 추가
- 단과대 목록 조회 api 추가
- 스프링부트 실행 시 단과대 데이터 db에 삽입하는 기능 추가
- `CommandLineRunner` 구현체 사용
- 단과대 테이블이 비어있으면 초기 데이터 삽입
- closed #3
> feat: #3 단과대 목록 조회 기능 추가

- src/main/kotlin/com/yourssu/scouter/common/business/domain/part/PartDto.kt
- src/main/kotlin/com/yourssu/scouter/common/implement/domain/part/Part.kt
- src/main/kotlin/com/yourssu/scouter/common/implement/support/initialization/DivisionsAndPartsInitializer.kt
- src/main/kotlin/com/yourssu/scouter/common/storage/domain/part/PartEntity.kt
- src/main/resources/application-local.yml
- Member 관련 api에서 `구분`도 함께 조회하는 경우가 많아서 `@ManyToOne`으로 연관관계 설정 추가
- closed #14
> refactor: #14 구분-파트 연관관계 설정

- src/main/kotlin/com/yourssu/scouter/common/application/domain/semester/CreateSemesterRequest.kt
- src/main/kotlin/com/yourssu/scouter/common/application/domain/semester/SemesterController.kt
- src/main/kotlin/com/yourssu/scouter/common/business/domain/semester/SemesterConverter.kt
- src/main/kotlin/com/yourssu/scouter/common/business/domain/semester/SemesterDto.kt
- src/main/kotlin/com/yourssu/scouter/common/business/domain/semester/SemesterService.kt
- src/main/kotlin/com/yourssu/scouter/common/implement/domain/semester/Semester.kt
- src/main/kotlin/com/yourssu/scouter/common/implement/domain/semester/SemesterRepository.kt
- src/main/kotlin/com/yourssu/scouter/common/implement/domain/semester/SemesterWriter.kt
- src/main/kotlin/com/yourssu/scouter/common/implement/domain/semester/Term.kt
- src/main/kotlin/com/yourssu/scouter/common/storage/domain/semester/SemesterEntity.kt
- src/main/kotlin/com/yourssu/scouter/common/storage/domain/semester/SemesterRepositoryImpl.kt
- Semester 도메인 필드 타입 변경
- 학기를 나타내는  `Term` enum 클래스 추가
- 필드 타입으로 연도는 `Year`, 학기는 `Term` 사용
- 이에 따라 converter와 entity 수정
- 날짜에 해당하는 학기를 구하는 기능 추가
- 학기 추가 api 추가
- 학기 삭제 api 추가
- closed #37
> feat: #37 학기 도메인 필드 타입 변경 및 학기 추가, 삭제 api 추가

- src/main/kotlin/com/yourssu/scouter/ats/application/domain/applicant/CreateApplicantRequest.kt
- src/main/kotlin/com/yourssu/scouter/ats/application/domain/applicant/ReadApplicantResponse.kt
- src/main/kotlin/com/yourssu/scouter/ats/application/domain/applicant/UpdateApplicantRequest.kt
- src/main/kotlin/com/yourssu/scouter/ats/business/domain/applicant/ApplicantService.kt
- src/main/kotlin/com/yourssu/scouter/ats/business/support/utils/ApplicantStateConverter.kt
- src/main/kotlin/com/yourssu/scouter/common/application/domain/semester/CreateSemesterRequest.kt
- src/main/kotlin/com/yourssu/scouter/common/application/domain/semester/ReadSemesterResponse.kt
- src/main/kotlin/com/yourssu/scouter/common/business/support/utils/SemesterConverter.kt
- src/main/kotlin/com/yourssu/scouter/hrms/application/domain/member/CreateMemberRequest.kt
- src/main/kotlin/com/yourssu/scouter/hrms/application/domain/member/ReadMemberResponse.kt
- src/main/kotlin/com/yourssu/scouter/hrms/application/domain/member/UpdateMemberRequest.kt
- src/main/kotlin/com/yourssu/scouter/hrms/business/domain/member/MemberService.kt
- src/main/kotlin/com/yourssu/scouter/hrms/business/support/utils/MemberRoleConverter.kt
- src/main/kotlin/com/yourssu/scouter/hrms/business/support/utils/MemberStateConverter.kt
- src/main/kotlin/com/yourssu/scouter/hrms/business/support/utils/NicknameConverter.kt
- 지원자 목록 조회 시 재학 학기를  `yy-n학기` 형식이 아니라 `yy-n` 형식으로 응답하도록 수정
- 멤버 생성 request dto에서 '비고' 필드에 대한 검증을 `@NotNull`로 수정
- request dto에서 필드 validation이 필드 레벨에서 동작하도록 어노테이션에 `@field:` 접두사 추가
- converter 클래스들을 `support.utils` 패키지로 이동
- closed #39
> fix: #39 지원자 목록 조회, 멤버 생성 시 api 명세에 맞지 않게 동작하는 문제 해결

- src/main/kotlin/com/yourssu/scouter/common/implement/support/security/oauth2/GoogleOAuth2Handler.kt
- src/main/kotlin/com/yourssu/scouter/common/implement/support/security/oauth2/GoogleOAuth2Properties.kt
- src/main/resources/application-local.yml
[문제]
- 개발 서버에 배포한 후 구글 소셜 로그인 테스트를 시도하였는데, 구글 소셜 로그인을 위한 리다이렉트 uri를 요청하였을 때 `액세스 차단됨: 이 앱의 요청이 잘못되었습니다` `400 오류: redirect_uri_mismatch` 발생
[원인]
- 기존에는 `oauth2.gogle.relative_redirect_uri`값을 설정해두고, `ServletUriComponentsBuilder.fromCurrentContextPath()`를 사용해서 요청이 들어온 uri를 기준으로 redirect_uri를 만들어서 사용했음
- 개발 서버에서는 로컬과 달리 ngix로 https 요청을 내부적으로 http 요청으로 변경함.
- 구글 클라우드 프로젝트에 등록한 redirect_uri는 `https://`로 시작하는 uri였기 때문에 uri_mismatch 오류 발생
- 구글 클라우드 프로젝트에서 Authorized redirect URI를 `http://`로 시작하는 uri로 변경하려고 했으나 정책 상 불가능 
[해결]
- `oauth2.google.redirect_uri` 설정값에 redirect_uri 직접 설정
- `ServletUriComponentsBuilder.fromCurrentContextPath()`와 조합하여 사용하지 않고 설정파일의 redirect_uri를 그대로 사용
- closed #43
> fix: #43 개발 환경에서 구글 소셜 로그인 시 400 오류가 발생하는 버그 해결

- src/main/kotlin/com/yourssu/scouter/ats/application/domain/applicant/CreateApplicantRequest.kt
- src/main/kotlin/com/yourssu/scouter/ats/application/domain/applicant/ReadApplicantResponse.kt
- src/main/kotlin/com/yourssu/scouter/ats/application/domain/applicant/UpdateApplicantRequest.kt
- src/main/kotlin/com/yourssu/scouter/ats/business/domain/applicant/ApplicantDto.kt
- src/main/kotlin/com/yourssu/scouter/ats/business/domain/applicant/ApplicantService.kt
- src/main/kotlin/com/yourssu/scouter/ats/business/domain/applicant/CreateApplicantCommand.kt
- src/main/kotlin/com/yourssu/scouter/ats/business/domain/applicant/UpdateApplicantCommand.kt
- src/main/kotlin/com/yourssu/scouter/ats/implement/domain/applicant/Applicant.kt
- src/main/kotlin/com/yourssu/scouter/ats/storage/domain/applicant/ApplicantEntity.kt
- 지원자 도메인 엔티티에 재학학기 필드 추가 (누락됨)
- 지원자 목록 조회 시 지원 학기가 아니라 재학 학기를 응답하도록 수정
- closed #47
> feat: #47 지원자 도메인, 엔티티에 재학학기 필드 추가

- src/main/kotlin/com/yourssu/scouter/ats/business/domain/applicant/ApplicantSyncService.kt
- src/main/kotlin/com/yourssu/scouter/common/business/domain/authentication/AuthenticationService.kt
- src/main/kotlin/com/yourssu/scouter/common/implement/domain/user/User.kt
- oauth2Id에 해당하는 유저가 존재하면 토큰 정보를 저장하지 않고 바로 반환하던 문제 해결
- 새 토큰 저장 후 반환하도록 수정
- closed #52
> fix: #52 로그인 시 가입된 사용자라면 토큰 저장 없이 반환하는 오류 해결

- src/main/kotlin/com/yourssu/scouter/ats/business/domain/applicant/ApplicantService.kt
- src/main/kotlin/com/yourssu/scouter/ats/implement/domain/applicant/Applicant.kt
- 지원자 도메인에 Comparable 구현
- 파트별 > 지원날짜 순으로 정렬
- closed #20
> feat: #20 지원자 목록 조회 시 정렬 기준 적용하는 기능 추가

- src/main/kotlin/com/yourssu/scouter/ats/application/domain/applicant/ApplicantController.kt
- src/main/kotlin/com/yourssu/scouter/ats/business/domain/applicant/ApplicantSyncService.kt
- src/main/kotlin/com/yourssu/scouter/common/business/domain/authentication/AuthenticationService.kt
- src/main/kotlin/com/yourssu/scouter/common/business/domain/authentication/OAuth2Service.kt
- src/main/kotlin/com/yourssu/scouter/common/implement/support/google/GoogleFormsClient.kt
- src/main/kotlin/com/yourssu/scouter/common/implement/support/google/UserResponse.kt
- src/main/kotlin/com/yourssu/scouter/hrms/application/domain/member/MemberController.kt
- src/main/kotlin/com/yourssu/scouter/hrms/business/domain/member/MemberService.kt
- src/main/kotlin/com/yourssu/scouter/hrms/business/domain/member/MemberSyncResult.kt
- src/main/kotlin/com/yourssu/scouter/hrms/business/domain/member/MemberSyncService.kt
- src/main/kotlin/com/yourssu/scouter/hrms/implement/domain/member/MemberReader.kt
- src/main/kotlin/com/yourssu/scouter/hrms/implement/domain/member/MemberRepository.kt
- src/main/kotlin/com/yourssu/scouter/hrms/storage/domain/member/JpaMemberRepository.kt
- src/main/kotlin/com/yourssu/scouter/hrms/storage/domain/member/MemberRepositoryImpl.kt
- 지원자 중 상태가 `최종합격`인 지원자 정보를 멤버에 반영하는 기능
- 지원자 도메인 엔티티에는 닉네임과 동아리 메일, 생일 등의 정보가 존재하지 않음
- 동아리 리쿠리팅 합격 시 합격자 정보를 별도의 구글폼으로 입력받고 있음
- 해당 구글폼 응답의 학번과 최종합격 지원자의 학번이 일치하면 동일한 학생으로 판단
→ `최종합격자 구글폼 응답`과 `최종합격 지원자 도메인 엔티티`의 정보를 활용하여 `멤버 도메인 엔티티` 생성 후 저장
- closed #36
> feat: #36 최종합격 지원자를 합격자 구글폼 응답을 바탕으로 동아리 멤버에 반영하는 api 추가

- src/main/kotlin/com/yourssu/scouter/ats/application/domain/applicant/ApplicantController.kt
- src/main/kotlin/com/yourssu/scouter/common/application/support/authentication/AuthUser.kt
- src/main/kotlin/com/yourssu/scouter/common/application/support/authentication/AuthUserInfo.kt
- src/main/kotlin/com/yourssu/scouter/common/application/support/authentication/AuthUserInfoArgumentResolver.kt
- src/main/kotlin/com/yourssu/scouter/common/application/support/authentication/LoginInterceptor.kt
- src/main/kotlin/com/yourssu/scouter/common/application/support/configuration/WebConfiguration.kt
- src/main/kotlin/com/yourssu/scouter/common/application/support/exception/LoginRequiredException.kt
- src/main/kotlin/com/yourssu/scouter/hrms/application/domain/member/MemberController.kt
- 로그인 관련 Interceptor 추가 (Authorization 헤더에 access token이 없으면 예외 반환)
- Argument Resolver 추가
- api에 적용
- closed #59
> feat: #59 인증 기능 적용

- src/main/kotlin/com/yourssu/scouter/common/implement/domain/semester/SemesterReader.kt
- src/main/kotlin/com/yourssu/scouter/hrms/business/domain/member/MemberService.kt
[문제]
- 멤버 정보 변경 시 파트가 빈 배열인 경우 요청은 정상처리되지만, 이후에 멤버 목록 조회 시 Internal Server Error 발생
[원인]
- 멤버 목록 조회 시 정렬할 때 멤버의 첫 번째 파트를 기준으로 정렬하고 있음
- 멤버 정보 변경 시 파트를 빈 배열로 하면 파트가 없는 것으로 처리되어서 멤버 도메인은 파트 정보를 빈 리스트로 들고 있음
- 멤버 정렬 시 첫 번째 파트를 기준으로 정렬하는데 첫 번째 파트가 없기 때문에 에러 발생
[해결]
- 서비스 규칙 상 모든 멤버는 하나 이상의 파트를 맡고 있어야 함
- 프론트에서 빈 리스트를 보내는 경우는 해당 멤버가 맡고 있는 파트가 없어서가 아니라, 파트를 변경하지 않았기 때문임
- 따라서, 멤버 정보 수정 요청에서 파트가 빈 배열일 경우, 파트를 null로 보낸 경우와 동일하게 처리(파트를 변경하지 않은 것으로 처리)하도록 수정
- closed #74
> fix: #74 멤버 정보 변경 시 파트를 빈 배열로 한 이후 멤버 목록 조회 시 에러가 발생하는 버그 해결

- src/main/kotlin/com/yourssu/scouter/ats/application/domain/applicant/ApplicantController.kt
- src/main/kotlin/com/yourssu/scouter/ats/business/domain/applicant/ApplicantService.kt
- src/main/kotlin/com/yourssu/scouter/ats/business/support/utils/ApplicantStateConverter.kt
- src/main/kotlin/com/yourssu/scouter/ats/implement/domain/applicant/ApplicantReader.kt
- src/main/kotlin/com/yourssu/scouter/ats/implement/domain/applicant/ApplicantRepository.kt
- src/main/kotlin/com/yourssu/scouter/ats/storage/domain/applicant/ApplicantRepositoryImpl.kt
- 지원자 목록 조회에서 필터링 시 다중 조건을 사용할 수 있도록 기능 추가
- 전체 목록 조회 후 애플리케이션 단에서 필터링하도록 구현함 (추후 Jpa Specification 적용 고려)
- closed #77
> feat: #77 지원자 다중 필터링 기능 추가

- src/main/kotlin/com/yourssu/scouter/ats/application/domain/applicant/ApplicantController.kt
- src/main/kotlin/com/yourssu/scouter/ats/application/domain/applicant/ApplicantSyncResponse.kt
- src/main/kotlin/com/yourssu/scouter/ats/business/domain/applicant/ApplicantSyncResult.kt
- src/main/kotlin/com/yourssu/scouter/ats/business/domain/applicant/ApplicantSyncService.kt
- src/main/kotlin/com/yourssu/scouter/common/implement/support/google/GoogleDriveQueryBuilder.kt
- src/main/kotlin/com/yourssu/scouter/common/implement/support/google/GoogleFormsClient.kt
- src/main/kotlin/com/yourssu/scouter/common/implement/support/google/GoogleFormsReader.kt
- src/main/kotlin/com/yourssu/scouter/common/implement/support/google/UserResponse.kt
- src/main/kotlin/com/yourssu/scouter/common/implement/support/initialization/DivisionsAndPartsInitializer.kt
- 구글폼 api에 사용되는 응답 dto 필드를 nullable하게 변경
- 2025년 1학기에 해당하는 지원서 제목에 맞게 구글 드라이브 api에 사용하는 쿼리 수정
- 구글폼에서 지원자 정보를 불러오는 로직 수정
- 파트 우선순위 오류 수정
- 파트명 변경된 파트에 대해 초기 파트명 변경
- closed #81
> refactor: #81 구글폼에서 지원자 정보를 불러오는 로직 리팩토링

- src/main/kotlin/com/yourssu/scouter/ats/application/domain/applicant/ApplicantController.kt
- src/main/kotlin/com/yourssu/scouter/ats/application/domain/applicant/ApplicantSyncController.kt
- src/main/kotlin/com/yourssu/scouter/ats/application/domain/applicant/ApplicantSyncResponse.kt
- src/main/kotlin/com/yourssu/scouter/ats/business/domain/applicant/ApplicantSyncResult.kt
- src/main/kotlin/com/yourssu/scouter/ats/business/domain/applicant/ApplicantSyncService.kt
- src/main/kotlin/com/yourssu/scouter/ats/implement/domain/applicant/ApplicantSyncLog.kt
- src/main/kotlin/com/yourssu/scouter/ats/implement/domain/applicant/ApplicantSyncLogReader.kt
- src/main/kotlin/com/yourssu/scouter/ats/implement/domain/applicant/ApplicantSyncLogRepository.kt
- src/main/kotlin/com/yourssu/scouter/ats/implement/domain/applicant/ApplicantSyncLogWriter.kt
- src/main/kotlin/com/yourssu/scouter/ats/storage/domain/applicant/ApplicantSyncLogEntity.kt
- src/main/kotlin/com/yourssu/scouter/ats/storage/domain/applicant/ApplicantSyncLogRepositoryImpl.kt
- src/main/kotlin/com/yourssu/scouter/ats/storage/domain/applicant/JpaApplicantSyncLogRepository.kt
- 구글폼에서 지원자 응답을 불러와서 지원자 목록에 저장할 때 폼 id와 응답 id를 기록하도록 함
- 지원자 저장 시 저장된 기록이 없는 지원자만 저장
- closed #84
> feat: 84 구글폼에서 지원자 정보를 불러올 때 새로운 응답만 불러오도록 하는 기능 추가

- src/main/kotlin/com/yourssu/scouter/common/application/domain/authentication/AuthenticationController.kt
- src/main/kotlin/com/yourssu/scouter/common/application/domain/authentication/OAuth2Controller.kt
- src/main/kotlin/com/yourssu/scouter/common/business/domain/authentication/OAuth2Service.kt
- src/main/kotlin/com/yourssu/scouter/common/implement/domain/authentication/OAuth2Handler.kt
- src/main/kotlin/com/yourssu/scouter/common/implement/support/security/oauth2/GoogleOAuth2Handler.kt
- src/main/kotlin/com/yourssu/scouter/common/implement/support/security/oauth2/GoogleOAuth2Properties.kt
- src/main/resources/application-local.yml
프론트 실배포 서버, qa용 서버, 개발환경(localhost 서버) 등 다양한 요청 주소에 동적으로 대응할 수 있도록 redirect url을 http request의 referer 헤더 값과 조합해서 반환
- closed #89
> feat: #91 oauth2 로그인 redirect uri를 프론트 출처에 따라 유동적으로 반환하는 기능 추가

- build.gradle.kts
- src/main/kotlin/com/yourssu/scouter/common/business/domain/mail/MailBodyFormat.kt
- src/main/kotlin/com/yourssu/scouter/common/business/domain/mail/MailData.kt
- src/main/kotlin/com/yourssu/scouter/common/business/domain/mail/MailSender.kt
- src/main/kotlin/com/yourssu/scouter/common/implement/domain/mail/MimeMessageBuilder.kt
- src/main/kotlin/com/yourssu/scouter/common/implement/domain/mail/MimeMessageBuilderResolver.kt
- src/main/kotlin/com/yourssu/scouter/common/implement/domain/mail/builder/MimeMessageCommonHeaderApplier.kt
- src/main/kotlin/com/yourssu/scouter/common/implement/domain/mail/builder/MultipartHtmlMimeMessageBuilder.kt
- src/main/kotlin/com/yourssu/scouter/common/implement/domain/mail/builder/PlainTextOnlyMimeMessageBuilder.kt
- src/main/kotlin/com/yourssu/scouter/common/implement/domain/mail/builder/SimpleHtmlMimeMessageBuilder.kt
- src/main/kotlin/com/yourssu/scouter/common/implement/support/exception/MailFailedException.kt
- src/main/kotlin/com/yourssu/scouter/common/implement/support/google/GoogleMailClient.kt
- src/main/kotlin/com/yourssu/scouter/common/implement/support/mail/GoogleMailSender.kt
- src/test/kotlin/com/yourssu/scouter/common/implement/support/mail/GoogleMailSenderTest.kt
- 구글로그인한 사용자의 access token과 구글 api 호출로 gmail 전송 가능
- 수신자, cc, bcc, 메일 제목, 메일 본문, 인라인 이미지(메일 본문에 삽입한 이미지), 첨부파일 설정해서 전송 가능
- plain text, 단순 html, 인라인 이미지와 첨부파일이 포함된 multipart html 모두 사용 가능하도록 확장성있게 설계
- closed #76
> feat: #76 메일 전송 기능 추가

- .gitignore
- env.example
- src/main/kotlin/com/yourssu/scouter/common/application/domain/authentication/AuthenticationController.kt
- src/main/kotlin/com/yourssu/scouter/common/application/domain/authentication/OAuth2Controller.kt
- src/main/kotlin/com/yourssu/scouter/common/application/domain/authentication/OAuth2LoginRequest.kt
- src/main/kotlin/com/yourssu/scouter/common/application/support/authentication/LoginInterceptor.kt
- src/main/kotlin/com/yourssu/scouter/common/application/support/configuration/RequestLoggingFilter.kt
- src/main/kotlin/com/yourssu/scouter/common/application/support/exception/CommonExceptionHandler.kt
- src/main/kotlin/com/yourssu/scouter/common/business/domain/authentication/AuthenticationService.kt
- src/main/kotlin/com/yourssu/scouter/common/business/domain/authentication/OAuth2Service.kt
- src/main/kotlin/com/yourssu/scouter/common/implement/domain/authentication/OAuth2Handler.kt
- src/main/kotlin/com/yourssu/scouter/common/implement/support/configuration/OpenFeignConfiguration.kt
- src/main/kotlin/com/yourssu/scouter/common/implement/support/security/oauth2/GoogleOAuth2Handler.kt
- src/main/kotlin/com/yourssu/scouter/common/implement/support/security/oauth2/GoogleOAuth2Properties.kt
- src/main/resources/application-local.yml
Google OAuth에서 redirect_uri_mismatch 발생. 
인가 단계와 토큰 교환 단계의 redirect_uri가 일치하지 않았음.
토큰 교환 시 referer 기반 calculateRedirectUri(referer) 사용으로 referer에 의존하여 값이 들쭉날쭉 달라졌음.
oauth2.google.redirect_uri(절대 URL) 설정 도입 및 우선 사용.
GoogleOAuth2Handler: 토큰 교환 요청의 redirect_uri를 절대값으로 고정. allowlist 검증 지원
application-*.yml: 환경별 redirect_uri와 allowed_redirect_uris 구성.
+) 로깅 강화: 실제 전송한 redirect_uri를 INFO로 기록
+) 부가: 요청/예외 로깅, refresh-token 처리 정비, env 변수화
- Google 정책상 인가와 토큰 교환의 redirect_uri는 완전 동일해야 하며, 절대 URL을 고정하는 것이 가장 안전
- referer 의존 계산은 프록시/호스트 전개(Nginx, 디버그 엔드포인트, localhost 등) 상황에서 변동성이 큼
- allowlist로 FE가 넘겨준 redirect_uri를 검증·허용하면 로컬/스테이징 전환도 통제 가능
closed #110 
...잘 고쳤는지 모르겠어요..ㅠㅡㅠ 아직 완전히 이해한건 아닌데 그냥 yml 에 redirect_uri을 고정시켜서 들쭉날쭉하는 걸 막았다는 느낌만 들어요...
> fix:#110 Google Oauth 리다이렉트 경로 mismatch

- build.gradle.kts
- src/main/kotlin/com/yourssu/scouter/ats/application/domain/applicant/ApplicantController.kt
- src/main/kotlin/com/yourssu/scouter/ats/application/domain/applicant/ApplicantSyncController.kt
- src/main/kotlin/com/yourssu/scouter/common/application/domain/authentication/AuthenticationController.kt
- src/main/kotlin/com/yourssu/scouter/common/application/domain/authentication/OAuth2Controller.kt
- src/main/kotlin/com/yourssu/scouter/common/application/domain/authentication/SwaggerOAuth2Controller.kt
- src/main/kotlin/com/yourssu/scouter/common/application/domain/college/CollegeController.kt
- src/main/kotlin/com/yourssu/scouter/common/application/domain/department/DepartmentController.kt
- src/main/kotlin/com/yourssu/scouter/common/application/domain/division/DivisionController.kt
- src/main/kotlin/com/yourssu/scouter/common/application/domain/mail/MailReservationController.kt
- src/main/kotlin/com/yourssu/scouter/common/application/domain/mail/template/MailTemplateController.kt
- src/main/kotlin/com/yourssu/scouter/common/application/domain/part/PartController.kt
- src/main/kotlin/com/yourssu/scouter/common/application/domain/semester/SemesterController.kt
- src/main/kotlin/com/yourssu/scouter/common/application/support/authentication/AuthUserInfo.kt
- src/main/kotlin/com/yourssu/scouter/common/application/support/configuration/SwaggerConfiguration.kt
- src/main/kotlin/com/yourssu/scouter/common/application/support/configuration/WebConfiguration.kt
- src/main/kotlin/com/yourssu/scouter/hrms/application/domain/member/MemberController.kt
- src/main/kotlin/com/yourssu/scouter/hrms/application/domain/member/MemberSyncController.kt
- src/main/resources/application-local.yml
- OAuth2 인증을 추가했습니다. OAuth2 인증 로직 테스트를 위한 것이 아니라 다른 API를 테스트하기 위한 인증이므로 GOOGLE로 고정되게 했습니다.
- SWAGGER_OAUTH_REDIRECTION_URL에는 환경에 맞는 swagger 리다이렉션 Url을 입력하면 됩니다. ex) http://localhost:8080/swagger-ui/oauth2-redirect.html
- 기본적인 설명은 전부 달아뒀습니다. 그런데 특정 학기로 멤버/지원자를 동기화시키는건 목적이 무엇인지 잘 모르겠어서 설명을 달지 않았습니다.
- 문서화 작업을 하다가 /applicants/include-from-forms 엔드포인트의 응답 코드가 노션에 나와있는 코드와 다른 것을 확인했습니다. 우선 코드대로 200으로 달아두었지만 201 응답으로 변경하는게 맞을 것 같습니다.
closed #73
> [#73]; docs: swagger api 문서화 추가

- src/main/kotlin/com/yourssu/scouter/common/application/domain/authentication/AuthenticationController.kt
- src/main/kotlin/com/yourssu/scouter/common/application/domain/authentication/LoginResponse.kt
- src/main/kotlin/com/yourssu/scouter/common/application/domain/authentication/TokenRefreshResponse.kt
- src/main/kotlin/com/yourssu/scouter/common/application/support/authentication/AuthUserInfoArgumentResolver.kt
- src/main/kotlin/com/yourssu/scouter/common/application/support/configuration/SwaggerConfiguration.kt
- src/main/kotlin/com/yourssu/scouter/common/business/domain/authentication/AuthenticationService.kt
- src/main/kotlin/com/yourssu/scouter/common/implement/support/exception/InvalidTokenMessages.kt
- src/main/kotlin/com/yourssu/scouter/common/implement/support/security/token/JwtTokenProcessor.kt
- src/test/kotlin/com/yourssu/scouter/common/implement/support/security/token/JwtTokenProcessorTest.kt
- 클라가 잘못된 토큰종류를 사용 (refresh만 보내야하는데 access토큰 보내기) -> 아마 이거일 것 같음
- 근데 페카가 "스펙상 accessToken에 종속되지 않은 API인 /refresh-token 호출시에는 요청 헤더에 accessToken을 넣지 않게 만드는 방식" 으로 변경 -> 이미 해결됨
그래서 이미 해결되었지만, 나중에 이런 오류가 났을때 원인파악을 빠르게 하기 위해 표준화방식으로 변경
BREAKING CHANGE: 
- 응답 토큰이 이제 “순수 JWT”로 반환. 클라가 요청 시에만 Authorization: Bearer <accessToken>로 조립 필요.
그외:
- 접두사 제거 발급, 수신 시 접두사 유무 허용
- 토큰 타입 클레임 추가 및 불일치 시 상세 에러 메시지 (ex. 액세스 토큰이 아닙니다)
- /refresh-token Authorization 헤더 무시, 바디 refreshToken만 사용
- 메시지 상수화(InvalidTokenMessages), 테스트 보강
<details>
<summary>구체적인 api변경사항 요약</summary>
`공통`
- 서버 응답 토큰은 “순수 JWT”로 반환. 응답 바디에 tokenType: "Bearer" 추가.
- 보호 API 호출 시에만 헤더로 Authorization: Bearer <accessToken> 조립.
`POST /oauth2/login`
- 응답: { tokenType: "Bearer", accessToken: "<JWT>", refreshToken: "<JWT>" }
`POST /refresh-token` …
> [#129]; feat: 표준 토큰 응답 적용 및 타입클레임 추가

- src/main/kotlin/com/yourssu/scouter/ats/application/domain/applicant/ApplicantSyncController.kt
- src/main/kotlin/com/yourssu/scouter/ats/application/domain/applicant/ApplicantSyncExtensions.kt
- src/main/kotlin/com/yourssu/scouter/common/application/support/configuration/SwaggerConfiguration.kt
- src/main/kotlin/com/yourssu/scouter/hrms/application/domain/member/MemberSyncController.kt
- src/main/kotlin/com/yourssu/scouter/hrms/application/domain/member/MemberSyncExtensions.kt
- src/main/kotlin/com/yourssu/scouter/hrms/application/domain/member/MemberSyncResponse.kt
- src/main/kotlin/com/yourssu/scouter/hrms/business/domain/member/MemberService.kt
- src/main/kotlin/com/yourssu/scouter/hrms/business/domain/member/MemberSyncResult.kt
- src/main/kotlin/com/yourssu/scouter/hrms/business/domain/member/MemberSyncService.kt
- src/test/kotlin/com/yourssu/scouter/hrms/application/domain/member/MemberSyncExtensionsTest.kt
applicants/include-from-forms 뿐만아니라 members도 201로 변환고려했으나
멤버가 “생길 수 있다면” 201을 쓸 수 있지만, members는 동기화 특성상 신규맴버가 생성될 수도 있고 아닐 수도 있음
-> 걍 200으로 단순화
**_서브이슈 133관련 작업_**
-> 에민 코멘트보고 클라의 응답 명확성을 위해 조건에 따라 members/200/201반환하도록 변경
++) 설계고려사항 refactor: 컨트롤러의 공통헤더 대신 extenstions 함수로 분리
closes #115
closes #133
> [#115]; refactor!: 잘못된 응답구조 변경
